module OdmFormats
  def get_machine_readable
    machine_readable = [
      'cdf',
      'csv',
      'csv.zip',
      'esri shapefile',
      'geojson',
      'iati',
      'ical',
      'ics',
      'json',
      'kml',
      'kmz',
      'netcdf',
      'nt',
      'ods',
      'psv',
      'psv.zip',
      'rdf',
      'rdfa',
      'rss',
      'shapefile',
      'shp',
      'shp.zip',
      'sparql',
      'sparql web form',
      'tsv',
      'ttl',
      'wms',
      'xlb',
      'xls',
      'xls.zip',
      'xlsx',
      'xml',
      'xml.zip',
    ]
    return machine_readable
  end

  def get_non_proprietary
    non_propr = [
      'ascii',
      'audio/mpeg',
      'bmp',
      'cdf',
      'csv',
      'csv.zip',
      'dbf',
      'geojson',
      'geotiff',
      'gzip',
      'html',
      'iati',
      'ical',
      'ics',
      'jpeg 2000',
      'json',
      'kml',
      'kmz',
      'mpeg',
      'netcdf',
      'nt',
      'ods',
      'pdf',
      'pdf/a',
      'png',
      'psv',
      'psv.zip',
      'rdf',
      'rdfa',
      'rss',
      'rtf',
      'sparql',
      'sparql web form',
      'tar',
      'tiff',
      'tsv',
      'ttl',
      'txt',
      'wms',
      'xml',
      'xml.zip',
      'zip',
    ]
    return non_propr
  end
end
